### ISSUE TITLE
Installation failed on Magisk Canary

### ISSUE THREAD

**Issue by xDonatello** [Magisk-Modules-Repo/callrecorder-skvalex#4]
On the latest version of Magisk Canary the module flash fails.

![image](https://user-images.githubusercontent.com/13498803/140438703-91540d47-f537-4336-9f7a-315f0f0adf8a.png)

**Comment by krokofant** [comment]
Reading the [module guide](https://topjohnwu.github.io/Magisk/guides.html):
> When your module is downloaded with the Magisk app, update-binary will be forcefully replaced with the latest module_installer.sh to ensure all installer uses up-to-date scripts. DO NOT try to add any custom logic in update-binary as it is pointless.

I fixed this issue in the linked PR. Since there are no release zips you need to download this, extract it and just zip the module files. There one folder too much in the github zip.
https://github.com/Magisk-Modules-Repo/callrecorder-skvalex/archive/c026cd1eb286841c6f3880b2f3902ad1e0aa6f3f.zip

**Comment by xDonatello** [comment]
Oh, I had completely forgotten that I created this issue. 😅
The problem was that I didn't replace the "update-binary" file in the META-INF folder.
As it was written in that same file. Sorry.

**Comment by xDonatello** [comment]
PS. I noticed that you replaced "update-binary" with the one from Magisk.
It's better that way 👍
